name: musga
description: "A personal music streaming app"
publish_to: 'none'
version: 1.0.0+1
flutter:
  uses-material-design: true

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  grpc: ^3.2.4
  protobuf: ^3.1.0
  http: ^1.3.0
  shared_preferences: ^2.5.2
  provider: ^6.1.1
  just_audio: ^0.9.36
  path_provider: ^2.1.1
  fixnum: ^1.1.0
  logging: ^1.2.0
  logger: ^2.0.2
  flutter_riverpod: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0 